export default defineEventHandler((_event) => {
    const config = useRuntimeConfig()

    // eslint-disable-next-line no-console
    // console.log({
    //     APP_URL: config.public.appUrl,
    //     SITE_KEY: config.public.siteKey,
    //     NUXT_SENDGRID_API_KEY: config.sendgridApiKey,
    //     NUXT_SENDGRID_EMAIL_TEMPLATE_ID: config.sendgridEmailTemplateId,
    //     NUXT_SENDGRID_FROM_EMAIL_ID: config.sendgridFromEmailId,
    //     NUXT_SENDGRID_SALES_TEAM_EMAILS: config.sendgridSalesTeamEmails,
    //     NUXT_GOOGLE_CAPTCHA_SECRET_KEY: config.googleCaptchaSecretKey,
    //     NUXT_JWT_TOKEN: config.jwtToken,
    //     NUXT_PUBLIC_GOOGLE_CLIENT_ID: config.public.googleClientId,
    //     NUXT_GOOGLE_CLIENT_SECRET: config.googleClientSecret,
    //     NUXT_PUBLIC_MICROSOFT_APP_ID: config.public.microsoftAppId,
    //     NUXT_MICROSOFT_APP_PASSWORD: config.microsoftAppPassword,
    //     NUXT_PUBLIC_MICROSOFT_REDIRECT_URI: config.public.microsoftRedirectUri,
    //     NUXT_GOOGLE_APPLICATION_CREDENTIALS_BASE64: config.googleApplicationCredentialsBase64,
    //     NUXT_PUBLIC_SLACK_CLIENT_ID: config.public.slackClientId,
    //     NUXT_SLACK_CLIENT_SECRET: config.slackClientSecret,
    //     NUXT_PUBLIC_SLACK_REDIRECT_URI: config.public.slackRedirectUri,
    //     NUXT_PUBLIC_BOT_ENDPOINT: config.public.botEndpoint,
    //     NUXT_AWS_REGION: config.awsRegion,
    //     NUXT_AWS_ACCESS_KEY_ID: config.awsAccessKeyId,
    //     NUXT_AWS_SECRET_ACCESS_KEY: config.awsSecretAccessKey,
    //     NUXT_AWS_BUCKET_NAME: config.awsBucketName,
    //     NUXT_AWS_FOLDER_NAME: config.awsFolderName,
    //     NUXT_DB_HOST: config.dbHost,
    //     NUXT_DB_PORT: config.dbPort,
    //     NUXT_DB_NAME: config.dbName,
    //     NUXT_DB_USER: config.dbUser,
    //     NUXT_DB_PASSWORD: config.dbPassword,
    // })

    return {
        APP_URL: config.public.appUrl,
        SITE_KEY: config.public.siteKey,
        NUXT_SENDGRID_API_KEY: config.sendgridApiKey,
        NUXT_SENDGRID_EMAIL_TEMPLATE_ID: config.sendgridEmailTemplateId,
        NUXT_SENDGRID_FROM_EMAIL_ID: config.sendgridFromEmailId,
        NUXT_SENDGRID_SALES_TEAM_EMAILS: config.sendgridSalesTeamEmails,
        NUXT_GOOGLE_CAPTCHA_SECRET_KEY: config.googleCaptchaSecretKey,
        NUXT_JWT_TOKEN: config.jwtToken,
        NUXT_PUBLIC_GOOGLE_CLIENT_ID: config.public.googleClientId,
        NUXT_GOOGLE_CLIENT_SECRET: config.googleClientSecret,
        NUXT_PUBLIC_MICROSOFT_APP_ID: config.public.microsoftAppId,
        NUXT_MICROSOFT_APP_PASSWORD: config.microsoftAppPassword,
        NUXT_PUBLIC_MICROSOFT_REDIRECT_URI: config.public.microsoftRedirectUri,
        NUXT_GOOGLE_APPLICATION_CREDENTIALS_BASE64: config.googleApplicationCredentialsBase64,
        NUXT_PUBLIC_SLACK_CLIENT_ID: config.public.slackClientId,
        NUXT_SLACK_CLIENT_SECRET: config.slackClientSecret,
        NUXT_PUBLIC_SLACK_REDIRECT_URI: config.public.slackRedirectUri,
        NUXT_PUBLIC_BOT_ENDPOINT: config.public.botEndpoint,
        NUXT_AWS_REGION: config.awsRegion,
        NUXT_AWS_ACCESS_KEY_ID: config.awsAccessKeyId,
        NUXT_AWS_SECRET_ACCESS_KEY: config.awsSecretAccessKey,
        NUXT_AWS_BUCKET_NAME: config.awsBucketName,
        NUXT_AWS_FOLDER_NAME: config.awsFolderName,
        NUXT_DB_HOST: config.dbHost,
        NUXT_DB_PORT: config.dbPort,
        NUXT_DB_NAME: config.dbName,
        NUXT_DB_USER: config.dbUser,
        NUXT_DB_PASSWORD: config.dbPassword,

    }
})